config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("DJANGO_ADMIN_URL", "admin/"), admin.site.urls),
    path("sentry-debug/", trigger_error),
]


# debug 모드일 때만 아래 실행
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views


app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>/", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetail.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views


app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
    path("reservations/", views.SeeReservationsView.as_view(), name="reservations"),
    path(
        "host-rooms/reservations",
        views.SeeHostRoomsReservations.as_view(),
        name="host-rooms-reservations",
    ),
]

reservations/models.py
import datetime
from django.db import models
from django.utils import timezone
from core import models as core_models


class BookedDay(models.Model):
    """ BookedDay Model Definition """

    day = models.DateField()
    reservation = models.ForeignKey(
        "Reservation", related_name="bookedDays", on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Days"

    def __str__(self):
        return str(self.day)


class Reservation(core_models.TimeStampedModel):

    """ Reservation Model Definition """

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled"),
    )

    status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING
    )
    check_in = models.DateField()
    check_out = models.DateField()
    guest = models.ForeignKey(
        "users.User", related_name="reservations", on_delete=models.CASCADE
    )
    room = models.ForeignKey(
        "rooms.Room", related_name="reservations", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.room} - {self.check_in}"

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            start = self.check_in
            end = self.check_out
            differece = end - start
            existing_booked_day = BookedDay.objects.filter(
                day__range=(start, end)
            ).exists()
            if existing_booked_day is False:
                super().save(*args, **kwargs)
                for i in range(differece.days + 1):
                    day = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)
                return
        return super().save(*args, **kwargs)

    def get_total_price(self):
        start = self.check_in
        end = self.check_out
        difference = end - start
        return difference.days * self.room.price

reservations/views.py
import datetime
from django.http import Http404
from django.views.generic import View
from django.contrib import messages
from django.shortcuts import redirect, reverse, render
from rooms import models as room_models
from . import models
from reviews import forms as review_forms


class CreateError(Exception):
    pass


def create(request, room, year, month, day):
    try:
        date_obj = datetime.datetime(year, month, day)
        room = room_models.Room.objects.get(pk=room)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError()
    except (room_models.Room.DoesNotExist, CreateError):
        messages.error(request, "Can't Reserve That Room")
        return redirect(reverse("core:home"))
    except models.BookedDay.DoesNotExist:
        reservation = models.Reservation.objects.create(
            guest=request.user,
            room=room,
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1),
        )
        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationDetailView(View):
    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        if not reservation or (
            reservation.guest != self.request.user
            and reservation.room.host != self.request.user
        ):
            raise Http404()
        form = review_forms.CreateReviewForm()

        return render(
            self.request,
            "reservations/detail.html",
            {"reservation": reservation, "form": form},
        )


def edit_reservation(request, pk, verb):
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    if not reservation or (
        reservation.guest != request.user and reservation.room.host != request.user
    ):
        raise Http404()
    if verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
    elif verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED
        models.BookedDay.objects.filter(reservation=reservation).delete()
    reservation.save()
    messages.success(request, "Reservation Updated")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))

templates/reservations/detail.html
  {% extends "base.html" %}

{% block page_title %}
    Reservation {{reservation.check_in}}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar%}

{% block content %}
    <div class="container mx-auto my-10 flex flex-col">

        <div class="border-t border-l border-r bg-cover bg-center h-56 rounded-t-lg" style="background-image: url({{reservation.room.first_photo}});"></div>
       
        <div class="flex flex-col items-start border-l border-r border-t border b">
            <div class="font-medium border-b py-8 px-5 w-full">
                {{reservation.check_in}} - {{reservation.check_out}} <span class="{% if reservation.status == 'pending' %} text-yellow-500 {% elif reservation.stauts == 'canceled' %} text-red-600 {% else %} text-teal-600 {% endif %}">{{reservation.get_status_display}}</span>

            </div>

            <span class="text-2xl border-b p-5 mt-2 w-full">
                {{reservation.room.name}}
            </span>

            <div class="flex p-5 border-b w-full">
                <div class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=reservation.room.host%}
                    <span class="mt-2 text-gray-500">{{reservation.room.host.first_name}}</span>
                </div>
                <div class="ml-5 flex flex-col">
                    <span class="font-medium mb-px">Contact your Airbnb Host</span>
                    <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk %}" class="font-medium text-teal-500">Send a Message</a>
                </div>
            </div>
            <div class="py-10 px-5  ">
            {% if reservation.status != 'canceled' %}
                {% if reservation.status == 'confirmed' and  reservation.is_finished %}
                    <span class="font-medium text-2xl w-full text-center block mb-5 ">Write your review</span>
                    <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-1/2 mx-auto ">
                        {% csrf_token %}
                        {{form}}
                        <button class="btn-link mt-5">Submit Review</button>
                    </form>  
                {% else %}
                    
                        {% if reservation.status == "pending" %}
                            <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}" class="btn-link block px-3">Cancel Reservation</a>
                            {% if reservation.host != user %}
                            <a href="{% url 'reservations:edit' reservation.pk 'confirm' %}" class="btn-link block px-3 mb-5">Confirm Reservation</a>
                            {% endif %}   
                        {% endif %}
                    
                {% endif %}
            {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/reservations/reservation_list.html
{% extends "base.html" %} {% block page_title %} Reservation List {% endblock page_title %}
{% load i18n%}

{% block content %}
<div class="container w-full mx-auto pb-10 flex flex-row justify-between h-75vh">
    <div class="w-1/5  mr-8 flex flex-col">
        <a href="{% url 'users:reservations' %}" class="p-2 font-medium text-gray-500 hover:text-gray-700 {% if cur_page == 'reservations' %} text-gray-600 {% endif %}">{% trans "Your Reservations" %}</a>
        <a href="{% url 'users:host-rooms-reservations' %}" class="p-2 font-medium text-gray-500 hover:text-gray-700 {% if cur_page == 'reservations-host' %} text-gray-600 {% endif %}">{% trans "Your Room's Status" %}</a>
    </div>
    <div class="w-4/5 border border-gray-400 overflow-auto">
        <div class="w-full bg-gray-300 text-gray-600 pl-5 pt-6 pb-6 font-medium">
            <span>Upcoming Reservations</span>
        </div>
        {% if not exist %}
            <span class="text-2xl font-medium text-center w-full block mt-8 text-gray-800">
             {% if cur_page == 'reservations' %}
                {% trans "You have no reservations." %}
             {% elif cur_page == 'reservations-host'%}
                {% trans "You have no rooms." %}
            {% endif %}
            </span>
        {% else %}
        <div class="w-full px-3">
            <div class="flex flex-row font-medium py-2 border-b border-gray-400 text-gray-700 text-sm">
                <span class="pl-3 w-2/12 ">Status</span>
                <span class="pl-3 w-4/12">Dates and Location</span>
                <span class="pl-3 w-3/12">{% if cur_page == 'reservations'%}Host{% elif cur_page == 'reservations-host' %}Guest{% endif %}</span>
                <span class="pl-3 w-3/12">Details</span>
            </div>
            {% for reservation in reservations %}
            <div class="mt-1 flex flex-row border-b border-gray-400 py-3">
                <div class="w-2/12 pl-3 text-m font-medium {% if reservation.status == 'pending' %} text-orange-500 {% elif reservation.status == 'confirmed' %} text-teal-700 {% else %} text-red-600 {% endif %}">{{reservation.status}}</div>
                <div class="w-4/12 pl-3 flex flex-col font-medium text-sm ">
                    <span class="text-gray-700">{{reservation.check_in | date:'M d'}} - {{reservation.check_out | date:'M d, Y'}}</span>
                    <a href="{% url 'rooms:detail' reservation.room.pk %}" class="text-teal-600">{{reservation.room.name}}</a>
                    <span class="text-gray-700">{{reservation.room.address}}</span>
                    <span class="text-gray-700">{{reservation.room.city}}, {{reservation.room.country.name}}</span>
                </div> 
                <div class="pl-3 flex flex-row w-3/12">
                    {% if cur_page == "reservations" %}
                        <div>
                        {% include "mixins/user_avatar.html" with user=reservation.room.host h_and_w='h-12 w-12' text='text-lg'%}
                        </div>
                        <div class="flex flex-col ml-4 font-medium text-m text-gray-700">
                            <span>{{reservation.room.host.first_name}} {{reservation.room.host.last_name}}</span>
                            <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk%}">
                                <i class="fas fa-envelope text-teal-500 mr-1"></i>Send Message</a>
                        </div>
                    {% elif cur_page == "reservations-host" %}
                        <div>
                        {% include "mixins/user_avatar.html" with user=reservation.guest h_and_w='h-12 w-12' text='text-lg'%}
                        </div>
                        <div class="flex flex-col ml-4 font-medium text-m text-gray-700">
                            <span>{{reservation.guest.first_name}} {{reservation.guest.last_name}}</span>
                            <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk%}">
                                <i class="fas fa-envelope text-teal-500 mr-1"></i>Send Message</a>
                        </div>
                    {% endif %}
                </div>
                <div class="pl-3 font-medium text-m flex flex-col ">
                    <span class="text-gray-700">${{reservation.get_total_price}} total</span>
                    <a href="{% url 'reservations:detail' reservation.pk %}" class="text-teal-600">Change or Cancel</a>
                </div>
            </div>
            {% endfor %}
        {% endif %}
        </div>
    </div>
</div>
{% endblock content %}